# Generated by Django 4.2.30 on 2026-10-07 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icon', models.CharField(default='💼', max_length=10)),
                ('color', models.CharField(default='#007AFF', max_length=20)),
                ('is_productive', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_goal', models.CharField(choices=[('focus', 'Deep Focus & Career Mastery'), ('fitness', 'Health & Physical Vitality'), ('mindfulness', 'Mindfulness & Mental Peace'), ('learning', 'Continuous Learning & Growth'), ('balance', 'Work-Life Harmony & Well-being')], default='focus', max_length=50)),
                ('daily_target_hours', models.FloatField(default=8.0)),
                ('preferred_reminder_time', models.TimeField(blank=True, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('streak_count', models.IntegerField(default=1)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('bio_motto', models.CharField(blank=True, default='Making every single hour intentional.', max_length=255)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'Auto/System')], default='system', max_length=20)),
                ('avatar_color', models.CharField(default='#007AFF', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('message', models.TextField()),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HourlyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hour', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('duration_seconds', models.IntegerField(default=3600)),
                ('unit_type', models.CharField(choices=[('hours', 'Hours'), ('minutes', 'Minutes'), ('seconds', 'Seconds')], default='hours', max_length=10)),
                ('energy_level', models.IntegerField(default=4)),
                ('completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tracker.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'hour'],
                'unique_together': {('user', 'date', 'hour')},
            },
        ),
    ]
