# Generated by Django 4.2.30 on 2026-10-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_smtpsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlylog',
            options={'ordering': ['date', 'hour', 'created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='hourlylog',
            unique_together=set(),
        ),
    ]
