# Generated by Django 4.2.30 on 2026-10-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_hourlylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
