# Generated by Django 4.2.30 on 2026-10-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_userprofile_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English (US / UK)'), ('es', 'Español (Spanish)'), ('fr', 'Français (French)'), ('de', 'Deutsch (German)'), ('it', 'Italiano (Italian)'), ('pt', 'Português (Portuguese)'), ('ru', 'Русский (Russian)'), ('zh-hans', '简体中文 (Chinese Simplified)'), ('zh-hant', '繁體中文 (Chinese Traditional)'), ('ja', '日本語 (Japanese)'), ('ko', '한국어 (Korean)'), ('ar', 'العربية (Arabic)'), ('hi', 'हिन्दी (Hindi)'), ('ta', 'தமிழ் (Tamil)'), ('te', 'తెలుగు (Telugu)'), ('bn', 'বাংলা (Bengali)'), ('mr', 'मराठी (Marathi)'), ('ur', 'اردو (Urdu)'), ('gu', 'ગુજરાતી (Gujarati)'), ('kn', 'ಕನ್ನಡ (Kannada)'), ('ml', 'മലയാളം (Malayalam)'), ('pa', 'ਪੰਜਾਬੀ (Punjabi)'), ('tr', 'Türkçe (Turkish)'), ('vi', 'Tiếng Việt (Vietnamese)'), ('th', 'ไทย (Thai)'), ('id', 'Bahasa Indonesia (Indonesian)'), ('ms', 'Bahasa Melayu (Malay)'), ('nl', 'Nederlands (Dutch)'), ('pl', 'Polski (Polish)'), ('sv', 'Svenska (Swedish)'), ('el', 'Ελληνικά (Greek)'), ('he', 'עברית (Hebrew)'), ('uk', 'Українська (Ukrainian)'), ('cs', 'Čeština (Czech)'), ('ro', 'Română (Romanian)'), ('hu', 'Magyar (Hungarian)'), ('da', 'Dansk (Danish)'), ('fi', 'Suomi (Finnish)'), ('no', 'Norsk (Norwegian)'), ('fil', 'Filipino / Tagalog'), ('sw', 'Kiswahili (Swahili)'), ('fa', 'فارسی (Persian)')], default='en', max_length=20),
        ),
    ]
