# Generated by Django 4.2.30 on 2026-10-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_custom_endpoint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini (Free Tier Available)'), ('groq', 'Groq Cloud (100% Free Ultra-Fast Tier)'), ('openai', 'OpenAI (GPT-4o / GPT-4o-mini / GPT-3.5)'), ('anthropic', 'Anthropic Claude (Claude 3.5 Sonnet / Haiku)'), ('openrouter', 'OpenRouter (Multi-Model Gateway w/ Free Models)'), ('custom', 'Custom / Local Endpoint (Ollama, vLLM, LM Studio)')], default='gemini', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
    ]
