# Generated by Django 4.2.30 on 2026-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_userprofile_ai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_mode',
            field=models.CharField(choices=[('cloud', 'Cloud AI Mode (Gemini, Groq, OpenAI, Claude, Ollama)'), ('local', 'Non-AI Local Engine Mode (100% Offline, Zero API Keys)')], default='cloud', max_length=20),
        ),
    ]
